---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    domain_name: "athena.com"  # Define your domain name here

  roles:
    - roles: k8s-cert-sync

    - role: check_domain_availability
      vars:
        domain_name: "anotherdomain.com"
        adcli_options: "--verbose"


---
- name: Deploy and manage MariaDB across multiple hosts
  hosts: db_servers
  become: true  # To run with sudo if needed
  gather_facts: yes

  vars_files:
    - vars/var.yml  # Dynamic variables for databases

  roles:
    - role: test_db  # Replace with your actual role name
