---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    domain_name: "athena.com"  # Define your domain name here

  roles:
    - roles: k8s-cert-sync

    - role: check_domain_availability
      vars:
        domain_name: "anotherdomain.com"
        adcli_options: "--verbose"


---
- name: Deploy and manage MariaDB across multiple hosts
  hosts: db_servers
  become: true  # To run with sudo if needed
  gather_facts: yes

  vars:
    db_servers_info:
      - { ip: "10.0.0.1", user: "root", password: "password1", db_name: "db1" }
      - { ip: "10.0.0.2", user: "root", password: "password2", db_name: "db2" }
      - { ip: "10.0.0.3", user: "root", password: "password3", db_name: "db3" }

  roles:
    - role: test_db  # Replace with your actual role name