---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    domain_name: "athena.com"  # Define your domain name here

  roles:
    - roles: k8s-cert-sync

    - role: check_domain_availability
      vars:
        domain_name: "anotherdomain.com"
        adcli_options: "--verbose"


---
- name: Deploy and manage MariaDB across multiple hosts
  hosts: db_servers
  become: true  # To run with sudo if needed
  gather_facts: yes

  roles:
    - role: test_db  # Replace with your actual role name
    
  vars:
  db_servers_info:
    - ip: "db1.example.com"
      port: 3306
      user: "user1"
      password: "password1"
      db_name: "test_db1"
      db_table: "test_table"
    - ip: "db2.example.com"
      port: 3306
      user: "user2"
      password: "password2"
      db_name: "test_db2"
      db_table: "test_table"

