---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    domain_name: "athena.com"  # Define your domain name here

  roles:
    - roles: k8s-cert-sync

    - role: check_domain_availability
      vars:
        domain_name: "anotherdomain.com"
        adcli_options: "--verbose"

