---
- name: Iterate over each MariaDB instance and perform operations
  block:
    - name: Create a test table on {{ db_info.ip }}
      community.mysql.mysql_db:
        login_user: "{{ db_info.user }}"
        login_password: "{{ db_info.password }}"
        login_host: "{{ db_info.ip }}"
        name: "{{ db_info.db_name }}"
        state: present
        collation: 'utf8_general_ci'
      ignore_errors: yes

    - name: Create a column in the test table on {{ db_info.ip }}
      community.mysql.mysql_query:
        login_user: "{{ db_info.user }}"
        login_password: "{{ db_info.password }}"
        login_host: "{{ db_info.ip }}"
        login_db: "{{ db_info.db_name }}"
        query: "CREATE TABLE IF NOT EXISTS {{ db_info.db_table }} (id INT AUTO_INCREMENT PRIMARY KEY, test_column VARCHAR(255));"

    - name: Insert a test row into the database on {{ db_info.ip }}
      community.mysql.mysql_query:
        login_user: "{{ db_info.user }}"
        login_password: "{{ db_info.password }}"
        login_host: "{{ db_info.ip }}"
        login_db: "{{ db_info.db_name }}"
        query: "INSERT INTO {{ db_info.db_table }} (test_column) VALUES ('test_data');"

    - name: Select the test row from the database on {{ db_info.ip }}
      community.mysql.mysql_query:
        login_user: "{{ db_info.user }}"
        login_password: "{{ db_info.password }}"
        login_host: "{{ db_info.ip }}"
        login_db: "{{ db_info.db_name }}"
        query: "SELECT test_column FROM {{ db_info.db_table }} WHERE test_column = 'test_data';"
      register: query_result

    - name: Verify the data was inserted correctly on {{ db_info.ip }}
      ansible.builtin.assert:
        that:
          - query_result.rowcount[0] == 1
        fail_msg: "Failed to find the inserted data in the database on {{ db_info.ip }}."


    - name: Delete the test row from the database on {{ db_info.ip }}
      community.mysql.mysql_query:
        login_user: "{{ db_info.user }}"
        login_password: "{{ db_info.password }}"
        login_host: "{{ db_info.ip }}"
        login_db: "{{ db_info.db_name }}"
        query: "DELETE FROM {{ db_info.db_table }} WHERE test_column = 'test_data';"

    - name: Verify the data was deleted from the database on {{ db_info.ip }}
      community.mysql.mysql_query:
        login_user: "{{ db_info.user }}"
        login_password: "{{ db_info.password }}"
        login_host: "{{ db_info.ip }}"
        login_db: "{{ db_info.db_name }}"
        query: "SELECT test_column FROM {{ db_info.db_table }} WHERE test_column = 'test_data';"
      register: delete_check

    - name: Ensure the data was deleted successfully on {{ db_info.ip }}
      ansible.builtin.assert:
        that:
          - delete_check.rowcount[0] == 0
        fail_msg: "Failed to delete the test data from the database on {{ db_info.ip }}."

    - name: Drop the test table from the database on {{ db_info.ip }}
      community.mysql.mysql_query:
        login_user: "{{ db_info.user }}"
        login_password: "{{ db_info.password }}"
        login_host: "{{ db_info.ip }}"
        login_db: "{{ db_info.db_name }}"
        query: "DROP TABLE IF EXISTS {{ db_info.db_table }};"